In [1]:
print("I am running")

I am running

In [2]:
import numpy as np
import pandas as pd

from sklearn.model_selection import cross_val_score 
from sklearn.linear_model import LogisticRegression

In [3]:
import seaborn as sns

In [4]:
df = pd.read_csv('train.csv')[['Age','Pclass','Parch','SibSp','Survived']]
df.dropna(inplace=True)

In [5]:
df.head()

    Age  Pclass  Parch  SibSp  Survived
0  22.0       3      0      1         0
1  38.0       1      0      1         1
2  26.0       3      0      0         1
3  35.0       1      0      1         1
4  35.0       3      0      0         0

In [6]:
x = df.iloc[:,0:4]

In [7]:
y = df.iloc[:,-1]

In [8]:
x.head()

    Age  Pclass  Parch  SibSp
0  22.0       3      0      1
1  38.0       1      0      1
2  26.0       3      0      0
3  35.0       1      0      1
4  35.0       3      0      0

In [9]:
y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [10]:
lr = LogisticRegression()

In [11]:
lr.fit(x,y)

LogisticRegression()

In [12]:
np.mean(cross_val_score(lr,x,y,scoring = 'accuracy',cv=20))

np.float64(0.6933333333333332)

# applying Feature construction

In [13]:
x['Family_size'] = x['SibSp'] + x['Parch'] + 1

In [14]:
x.head()

    Age  Pclass  Parch  SibSp  Family_size
0  22.0       3      0      1            2
1  38.0       1      0      1            2
2  26.0       3      0      0            1
3  35.0       1      0      1            2
4  35.0       3      0      0            1

In [15]:
def categorize_family(size):
    if size == 1 :
        return 0 
    elif size >= 2 and size <= 4 :
        return 1 
    return 2

In [16]:
x['Family_size']

0      2
1      2
2      1
3      2
4      1
      ..
885    6
886    1
887    1
889    1
890    1
Name: Family_size, Length: 714, dtype: int64

In [17]:
x['Family_type'] = x['Family_size'].apply(categorize_family)

In [18]:
x['Family_type']

0      1
1      1
2      0
3      1
4      0
      ..
885    2
886    0
887    0
889    0
890    0
Name: Family_type, Length: 714, dtype: int64

In [19]:
x.drop(columns=['SibSp','Parch','Family_size'],inplace=True)

In [20]:
x

      Age  Pclass  Family_type
0    22.0       3            1
1    38.0       1            1
2    26.0       3            0
3    35.0       1            1
4    35.0       3            0
..    ...     ...          ...
885  39.0       3            2
886  27.0       2            0
887  19.0       1            0
889  26.0       1            0
890  32.0       3            0

[714 rows x 3 columns]

In [21]:
np.mean(cross_val_score(lr,x,y,cv=20))

np.float64(0.7003174603174602)

# Always keep in mind Is there any way to apply feature construction or feature engineering

In [22]:
# feature splinting

In [23]:
df = pd.read_csv('train.csv')

In [24]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [25]:
df.dropna(inplace=True)

In [26]:
# here the name column is not tidy that means it has a lot of values associated with it

In [65]:
df['Name'].str.split(', ',expand=True)[1].str.split('.',expand= True)[0]

1       Mrs
3       Mrs
6        Mr
10     Miss
11     Miss
       ...
871     Mrs
872      Mr
879     Mrs
887    Miss
889      Mr
Name: 0, Length: 183, dtype: object

1      Mrs. John Bradley (Florence Briggs Thayer)
3              Mrs. Jacques Heath (Lily May Peel)
6                                   Mr. Timothy J
10                           Miss. Marguerite Rut
11                                Miss. Elizabeth
                          ...
871        Mrs. Richard Leonard (Sallie Monypeny)
872                                Mr. Frans Olof
879         Mrs. Thomas Jr (Lily Alexenia Wilson)
887                          Miss. Margaret Edith
889                               Mr. Karl Howell
Name: Title, Length: 183, dtype: object

In [38]:
df['Name'].values

array(['Cumings, Mrs. John Bradley (Florence Briggs Thayer)',
       'Futrelle, Mrs. Jacques Heath (Lily May Peel)',
       'McCarthy, Mr. Timothy J', 'Sandstrom, Miss. Marguerite Rut',
       'Bonnell, Miss. Elizabeth', 'Beesley, Mr. Lawrence',
       'Sloper, Mr. William Thompson', 'Fortune, Mr. Charles Alexander',
       'Harper, Mrs. Henry Sleeper (Myna Haxtun)',
       'Ostby, Mr. Engelhart Cornelius', 'Harris, Mr. Henry Birkhardt',
       'Nye, Mrs. (Elizabeth Ramell)', 'Moen, Mr. Sigurd Hansen',
       'Fortune, Miss. Mabel Helen', 'Chaffee, Mr. Herbert Fuller',
       'Goldschmidt, Mr. George B', 'Greenfield, Mr. William Bertram',
       'White, Mr. Richard Frasar', 'Porter, Mr. Walter Chamberlain',
       'Baxter, Mr. Quigg Edmond', 'Webber, Miss. Susan',
       'White, Mr. Percival Wayland', 'Newsom, Miss. Helen Monypeny',
       'Futrelle, Mr. Jacques Heath', 'Giglio, Mr. Victor',
       'Navratil, Mr. Michel ("Louis M Hoffman")',
       'Pears, Mrs. Thomas (Edith Wearne)', 'Van der hoef, Mr. Wyckoff',
       'Smith, Mr. James Clinch', 'Isham, Miss. Ann Elizabeth',
       'Becker, Master. Richard F', 'Navratil, Master. Michel M',
       'Brown, Mrs. James Joseph (Margaret Tobin)',
       'Lurette, Miss. Elise', 'Strom, Miss. Telma Matilda',
       'Blank, Mr. Henry', 'Newell, Miss. Madeleine',
       'Bazzani, Miss. Albina', 'Hoyt, Mr. Frederick Maxfield',
       'Harris, Mrs. Henry Birkhardt (Irene Wallach)',
       'Minahan, Dr. William Edward', 'Beckwith, Mr. Richard Leonard',
       'Strom, Mrs. Wilhelm (Elna Matilda Persson)',
       'Stead, Mr. William Thomas', 'Cherry, Miss. Gladys',
       'Taussig, Mr. Emil', 'Harrison, Mr. William',
       'Graham, Mrs. William Thompson (Edith Junkins)',
       'Bissette, Miss. Amelia', 'Natsch, Mr. Charles H',
       'Andrews, Miss. Kornelia Theodosia',
       'Bishop, Mrs. Dickinson H (Helen Walton)',
       'Levy, Mr. Rene Jacques', 'Allison, Miss. Helen Loraine',
       'Baxter, Mrs. James (Helene DeLaudeniere Chaput)',
       'Allison, Master. Hudson Trevor',
       'Penasco y Castellana, Mrs. Victor de Satode (Maria Josefa Perez de Soto y Vallejo)',
       'Francatelli, Miss. Laura Mabel', 'Hays, Miss. Margaret Bechstein',
       'Ryerson, Miss. Emily Borie', 'Wick, Miss. Mary Natalie',
       'Spedden, Mrs. Frederic Oakley (Margaretta Corning Stone)',
       'Young, Miss. Marie Grice', 'Ball, Mrs. (Ada E Hall)',
       'Hippach, Miss. Jean Gertrude', 'Partner, Mr. Austen',
       'Graham, Mr. George Edward', 'Pears, Mr. Thomas Clinton',
       'Burns, Miss. Elizabeth Margaret', 'Blackwell, Mr. Stephen Weart',
       'Navratil, Master. Edmond Roger', 'Fortune, Miss. Alice Elizabeth',
       'Brown, Miss. Amelia "Mildred"', 'Bowerman, Miss. Elsie Edith',
       'Warren, Mrs. Frank Manley (Anna Sophia Atkinson)',
       'Aubart, Mme. Leontine Pauline', 'Harder, Mr. George Achilles',
       'Widener, Mr. Harry Elkins', 'Carter, Mr. William Ernest',
       'Newell, Miss. Marjorie',
       'Sandstrom, Mrs. Hjalmar (Agnes Charlotta Bengtsson)',
       'Minahan, Miss. Daisy E', 'Pickard, Mr. Berk (Berk Trembisky)',
       'Bjornstrom-Steffansson, Mr. Mauritz Hakan',
       'Silvey, Mr. William Baird', 'Carter, Miss. Lucile Polk',
       'Fortune, Mr. Mark', 'Dodge, Master. Washington',
       'Peuchen, Major. Arthur Godfrey',
       'Foreman, Mr. Benjamin Laventall', 'Goldenberg, Mr. Samuel L',
       'Millet, Mr. Francis Davis', 'Anderson, Mr. Harry',
       'Gee, Mr. Arthur H',
       'Jerwan, Mrs. Amin S (Marie Marthe Thuillard)',
       'Bishop, Mr. Dickinson H',
       'Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)',
       'Kent, Mr. Edward Austin', 'Molson, Mr. Harry Markland',
       'Eustis, Miss. Elizabeth Mussey',
       'Allison, Mrs. Hudson J C (Bessie Waldo Daniels)',
       'Maioni, Miss. Roberta',
       'Penasco y Castellana, Mr. Victor de Satode',
       'McGough, Mr. James Robert', 'Walker, Mr. William Anderson',
       'Lemore, Mrs. (Amelia Milley)', 'Perreault, Miss. Anne',
       'Hippach, Mrs. Louis Albert (Ida Sophia Fischer)',
       'Butt, Major. Archibald Willingham',
       'Frolicher, Miss. Hedwig Margaritha', 'Crosby, Miss. Harriet R',
       'Douglas, Mr. Walter Donald', 'Thayer, Mr. John Borland Jr',
       'Duff Gordon, Lady. (Lucille Christiana Sutherland) ("Mrs Morgan")',
       'Taussig, Mrs. Emil (Tillie Mandelbaum)',
       'Appleton, Mrs. Edward Dale (Charlotte Lamson)',
       'Flynn, Mr. John Irwin ("Irving")',
       'Silvey, Mrs. William Baird (Alice Munger)',
       'Thayer, Mrs. John Borland (Marian Longstreth Morris)',
       'Ross, Mr. John Hugo', 'Taussig, Miss. Ruth',
       'Frolicher-Stehli, Mr. Maxmillian',
       'Stephenson, Mrs. Walter Bertram (Martha Eustis)',
       'Duff Gordon, Sir. Cosmo Edmund ("Mr Morgan")',
       'Shutes, Miss. Elizabeth W', 'Becker, Miss. Marion Louise',
       'Kimball, Mr. Edwin Nelson Jr', 'Sutton, Mr. Frederick',
       'Longley, Miss. Gretchen Fiske',
       'Barkworth, Mr. Algernon Henry Wilson',
       'Stahelin-Maeglin, Dr. Max', 'Sagesser, Mlle. Emma',
       'Harper, Mr. Henry Sleeper', 'Simonius-Blumer, Col. Oberst Alfons',
       'Newell, Mr. Arthur Webster', 'Colley, Mr. Edward Pomeroy',
       'Davidson, Mr. Thornton', 'Cardeza, Mr. Thomas Drake Martinez',
       'Hassab, Mr. Hammad', 'Madill, Miss. Georgette Alexandra',
       'Dick, Mr. Albert Adrian', 'Thayer, Mr. John Borland',
       'Humblen, Mr. Adolf Mathias Nicolai Olsen',
       'Astor, Mrs. John Jacob (Madeleine Talmadge Force)',
       'Silverthorne, Mr. Spencer Victor',
       'Calderhead, Mr. Edward Pennington',
       'Mayne, Mlle. Berthe Antonine ("Mrs de Villiers")',
       'Taylor, Mr. Elmer Zebley',
       'Soholt, Mr. Peter Andreas Lauritz Andersen',
       'Endres, Miss. Caroline Louise',
       'Troutt, Miss. Edwina Celia "Winnie"',
       'Chambers, Mr. Norman Campbell', 'Allen, Miss. Elisabeth Walton',
       'Lesurer, Mr. Gustave J', 'Cavendish, Mr. Tyrell William',
       'Ryerson, Miss. Susan Parker "Suzette"',
       'Crosby, Capt. Edward Gifford', 'Marvin, Mr. Daniel Warner',
       'Moor, Master. Meier',
       'Rothes, the Countess. of (Lucy Noel Martha Dyer-Edwards)',
       'Carter, Mrs. William Ernest (Lucile Polk)',
       'Hogeboom, Mrs. John C (Anna Andrews)', 'Mack, Mrs. (Mary)',
       'Robert, Mrs. Edward Scott (Elisabeth Walton McMillan)',
       'Dick, Mrs. Albert Adrian (Vera Gillespie)',
       'Long, Mr. Milton Clyde', 'Guggenheim, Mr. Benjamin',
       'Leader, Dr. Alice (Farnham)',
       'Carter, Master. William Thornton II', 'Andrews, Mr. Thomas Jr',
       'Chambers, Mrs. Norman Campbell (Bertha Griggs)',
       'Hays, Mrs. Charles Melville (Clara Jennings Gregg)',
       'Moor, Mrs. (Beila)', 'Compton, Miss. Sara Rebecca',
       'Lines, Miss. Mary Conover', 'Daly, Mr. Peter Denis ',
       'Swift, Mrs. Frederick Joel (Margaret Welles Barron)',
       'Roebling, Mr. Washington Augustus II',
       'Beckwith, Mrs. Richard Leonard (Sallie Monypeny)',
       'Carlsson, Mr. Frans Olof',
       'Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)',
       'Graham, Miss. Margaret Edith', 'Behr, Mr. Karl Howell'],
      dtype=object)

In [45]:
split_data = df['Name'].str.split(', ')

In [56]:
split_data.values[180][1].split('.')[0]

'Mrs'

In [29]:
df['Title'].isnull().sum()

np.int64(0)